### ISSUE TITLE
Unclear prupose of `dir-cmd`

### ISSUE THREAD

**Issue by devgioele** [romshark/templier#16]
It is unclear to me how I should specify `dir-cmd` and `dir-work` in the config.

In my small project I just have a `main.go` file in the project's root directory.
Even when I tried to move the `main.go` file to `cmd/server/server.go`, templier prints:

```
ERR: running ./cmd/server/: exec: no command
ERR: health check: waiting for process: exec: not started
```

My config:
```yml
proxy-timeout: 10s
lint: false

format: true

templier-host: "localhost:7331"

log:
  level: erronly
  clear-on:
  print-js-debug-logs: true

debounce: 50ms


tls: null

compiler:
  gcflags:
  ldflags:
  asmflags:
  trimpath:
  race:
  tags:
  p:
  msan:
  env:
    CGO_ENABLED: 0

app:
  dir-src-root: ./
  exclude:
    - .*
    - "*~"
  dir-cmd: ./cmd/server/
  dir-work: ./
  host: http://localhost:8080
  flags:

custom-watchers:
  - name: "Reload on JS/CSS changes"
    cmd:
    include: ["*.js", "*.jsx", "*.css"]
    exclude:
    fail-on-error: true
    debounce:
    requires: reload

  - name: "Restart on config change"
    cmd:
    include: ["*.yaml", "*.yml", "*.toml"]
    exclude: []
    fail-on-error:
    debounce:
    requires: restart
```
